name: Fortune Teller
on: # push
  schedule:
    - cron: '0 8 * * *'

jobs:
  fortune_telling:
    runs-on: ubuntu-latest
    steps:
      - name: Install Fortune
        run: |
          sudo apt install fortune-mod
          sudo apt-get install --no-install-recommends curl
      - name: Speak out fortune
        env:
          url: ${{ secrets.slack_webhook_url }}
        run: |
          export PATH=$PATH:/usr/games
          msg=$(fortune)
          echo $msg
          curl -X POST --data-urlencode "payload={\"username\": \"fortune-teller\", \"text\": \"$msg\"}" $url
